
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import OperationsContractArtifactJson from './operations-Operations.json' with { type: 'json' };
export const OperationsContractArtifact = loadContractArtifact(OperationsContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract Operations;
 */
export class OperationsContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, OperationsContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): OperationsContract {
    return Contract.at(address, OperationsContract.artifact, wallet) as OperationsContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, registry_addr: AztecAddressLike) {
    return new DeployMethod<OperationsContract>(PublicKeys.default(), wallet, OperationsContractArtifact, (instance, wallet) => OperationsContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, registry_addr: AztecAddressLike) {
    return new DeployMethod<OperationsContract>(publicKeys, wallet, OperationsContractArtifact, (instance, wallet) => OperationsContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof OperationsContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<OperationsContract['methods'][M]>
  ) {
    return new DeployMethod<OperationsContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      OperationsContractArtifact,
      (instance, wallet) => OperationsContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return OperationsContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(OperationsContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'has_voted' | 'auth_notes' | 'revocations' | 'registry' | 'vote_instructions'> {
      return {
        has_voted: {
      slot: new Fr(1n),
    },
auth_notes: {
      slot: new Fr(2n),
    },
revocations: {
      slot: new Fr(3n),
    },
registry: {
      slot: new Fr(4n),
    },
vote_instructions: {
      slot: new Fr(6n),
    }
      } as ContractStorageLayout<'has_voted' | 'auth_notes' | 'revocations' | 'registry' | 'vote_instructions'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** _mark_voted_public(agent: struct) */
    _mark_voted_public: ((agent: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** configure_agent_registration(agent: struct, is_registered: boolean) */
    configure_agent_registration: ((agent: AztecAddressLike, is_registered: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(registry_addr: struct) */
    constructor: ((registry_addr: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** consume_vote_instruction(agent: struct) */
    consume_vote_instruction: ((agent: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_has_voted(agent: struct) */
    get_has_voted: ((agent: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** issue_vote_instruction(agent: struct, candidate: field) */
    issue_vote_instruction: ((agent: AztecAddressLike, candidate: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
