
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import PrivateVotingContractArtifactJson from './private_voting-PrivateVoting.json' with { type: 'json' };
export const PrivateVotingContractArtifact = loadContractArtifact(PrivateVotingContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract PrivateVoting;
 */
export class PrivateVotingContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, PrivateVotingContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): PrivateVotingContract {
    return Contract.at(address, PrivateVotingContract.artifact, wallet) as PrivateVotingContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, operations_addr: AztecAddressLike, vote_start_delay_seconds: (bigint | number), vote_duration_seconds: (bigint | number)) {
    return new DeployMethod<PrivateVotingContract>(PublicKeys.default(), wallet, PrivateVotingContractArtifact, (instance, wallet) => PrivateVotingContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike, operations_addr: AztecAddressLike, vote_start_delay_seconds: (bigint | number), vote_duration_seconds: (bigint | number)) {
    return new DeployMethod<PrivateVotingContract>(publicKeys, wallet, PrivateVotingContractArtifact, (instance, wallet) => PrivateVotingContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof PrivateVotingContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<PrivateVotingContract['methods'][M]>
  ) {
    return new DeployMethod<PrivateVotingContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      PrivateVotingContractArtifact,
      (instance, wallet) => PrivateVotingContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PrivateVotingContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(PrivateVotingContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'tally' | 'vote_ended' | 'vote_start_timestamp' | 'vote_deadline_timestamp' | 'operations_contract'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
tally: {
      slot: new Fr(2n),
    },
vote_ended: {
      slot: new Fr(3n),
    },
vote_start_timestamp: {
      slot: new Fr(4n),
    },
vote_deadline_timestamp: {
      slot: new Fr(6n),
    },
operations_contract: {
      slot: new Fr(8n),
    }
      } as ContractStorageLayout<'admin' | 'tally' | 'vote_ended' | 'vote_start_timestamp' | 'vote_deadline_timestamp' | 'operations_contract'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** cast_vote() */
    cast_vote: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct, operations_addr: struct, vote_start_delay_seconds: integer, vote_duration_seconds: integer) */
    constructor: ((admin: AztecAddressLike, operations_addr: AztecAddressLike, vote_start_delay_seconds: (bigint | number), vote_duration_seconds: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** end_vote() */
    end_vote: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_deadline_timestamp() */
    get_deadline_timestamp: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_start_timestamp() */
    get_start_timestamp: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_vote(candidate: field) */
    get_vote: ((candidate: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_vote_finished() */
    is_vote_finished: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
